[[items]]
title = "Hugrid Theme"
image = "images/lion.jpg"
alt = "Hugrid Theme"
description = "A simple grid theme for Hugo. A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
url = "https://github.com/aerohub/hugrid"
cropOptions = "right q01"
command = "Crop"
[[items]]
title = "Hugrid Theme"
image = "images/lion2.jpg"
alt = "Hugrid Theme"
description = "A simple grid theme for Hugo. A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
url = "https://github.com/aerohub/hugrid"
