[[items]]
title = "Framebags"
image = "framebag.jpg"
alt = "Hugrid Theme"
description = "fits like a glove"
url = "framebag"
cropOptions = "center q50"
command = "Fill"

[[items]]
title = "Arschbombe"
image = "ab.jpg"
alt = "Hugrid Theme"
description = "For times when the Arschrakete is too much"
url = "arschbombe"
cropOptions = "center q50"
command = "Fill"


[[items]]
title = "Saddlebag"
image = "st_c.jpg"
alt = "Hugrid Theme"
description = "a small bag for tubes and tools"
url = "st"
cropOptions = "center q50"
command = "Fill"

[[items]]
title = "Barrelbag"
image = "barrel.jpg"
description = "Round and reliable"
url = "barrel"
cropOptions = "center"
command = "Fill"

[[items]]
title = "Stembag"
image = "a.jpg"
cropOptions = "bottom q50"
command = "Fill"
alt = "Hugrid Theme"
description = "perfect for haribo, or a water bottle"
url = "fb"



[[items]]
title = "Trifold"
image = "trifold1.jpg"
description = "A lightweight wallet for cards and cash"
url = "trifold"
cropOptions = "center"
command = "Fill"

[[items]]
title = "Schlüsselmappe"
image = "mappe.jpg"
description = "Never lose your keys again"
url = "schlslmappe"
cropOptions = "center"
command = "Fill"


[[items]]
title = "Everyday Pouch"
image = "e.jpg"
description = "A pouch to keep organised and tidy"
url = "pouch"
cropOptions = "center"
command = "Fill"


