[[items]]
title = "Saddlebag"
image = "c.jpg"
alt = "Hugrid Theme"
description = "a small bag for tubes and tools"
url = "bikebags/st"
cropOptions = "center q50"
command = "Fill"
[[items]]
title = "Stembag"
image = "a.jpg"
cropOptions = "bottom q50"
command = "Fill"
alt = "Hugrid Theme"
description = "perfect for haribo, or a water bottle"
url = "bikebags/fb"
